In [1]:
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [2]:
df=pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [4]:
df['Rzscore']=(df['RestingBP']-df.RestingBP.mean())/(df.RestingBP.std())
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Rzscore
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812
...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660

In [5]:
df['Czscore']=(df['Cholesterol']-df.Cholesterol.mean())/(df.Cholesterol.std())
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Rzscore,Czscore
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578

In [6]:
df['Mzscore']=(df['MaxHR']-df.MaxHR.mean())/(df.MaxHR.std())
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Rzscore,Czscore,Mzscore
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452

In [7]:
df['Ozscore']=(df['Oldpeak']-df.Oldpeak.mean())/(df.Oldpeak.std())
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Rzscore,Czscore,Mzscore,Ozscore
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.824621,1.382175,-0.831979
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.171867,0.753746,0.105606
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.769768,-1.524307,-0.831979
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.138964,-1.131539,0.574398
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.034736,-0.581664,-0.831979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.596068,-0.188897,0.293123
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.053020,0.164595,2.355810
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.619830,-0.856602,0.293123
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.340090,1.460728,-0.831979
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.217578,1.421452,-0.831979

In [14]:
dfnooutliers=df[(((df.Rzscore>-3) & (df.Rzscore<3)) & ((df.Czscore>-3) & (df.Czscore<3)) & ((df.Mzscore>-3) & (df.Mzscore<3)) & ((df.Mzscore>-3) & (df.Mzscore<3)))]
#removing outliers

In [17]:
dfnooutliers.shape

(906, 16)

In [18]:
newdf=dfnooutliers.drop(['Rzscore','Czscore','Mzscore','Ozscore'],axis='columns')
newdf
#removing zscore columns

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [19]:
dfwithouttext=pd.get_dummies(newdf,drop_first=True)
dfwithouttext #converting text data to numeric using one hot encoding

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,1,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,1,0,1,0,0,0,1

In [22]:
x=dfwithouttext.drop(['HeartDisease'],axis='columns')
y=dfwithouttext.HeartDisease
scaler=StandardScaler()
xscaled=scaler.fit_transform(x,y)
xscaled

array([[-1.43268734,  0.46074981,  0.848846  , ..., -0.8232726 ,
        -0.99779493,  1.14251631],
       [-0.47787471,  1.62434375, -0.16934854, ..., -0.8232726 ,
         1.00220995, -0.87526103],
       [-1.75095822, -0.12104716,  0.79279859, ..., -0.8232726 ,
        -0.99779493,  1.14251631],
       ...,
       [ 0.37084763, -0.12104716, -0.62706901, ...,  1.2146645 ,
         1.00220995, -0.87526103],
       [ 0.37084763, -0.12104716,  0.35376058, ..., -0.8232726 ,
         1.00220995, -0.87526103],
       [-1.64486793,  0.34439041, -0.21605471, ..., -0.8232726 ,
        -0.99779493,  1.14251631]])

In [23]:
xtrain,xtest,ytrain,ytest=train_test_split(xscaled,y,test_size=0.2)
model=SVC()
model.fit(xtrain,ytrain)

SVC()

In [24]:
model.score(xtest,ytest)

0.8846153846153846

In [25]:
bagmodel=BaggingClassifier(
        base_estimator=SVC(),
        n_estimators=100,
        max_samples=0.8,
        oob_score=True,
        random_state=0
)
bagmodel.fit(xtrain,ytrain)

C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

BaggingClassifier(base_estimator=SVC(), max_samples=0.8, n_estimators=100,
                  oob_score=True, random_state=0)

In [27]:
bagmodel.oob_score_

0.8674033149171271

In [28]:
bagmodel.score(xtest,ytest)##bag model with standalone support vectore machine

0.8846153846153846

In [29]:
scores=cross_val_score(SVC(),x,y,cv=5)
scores.mean()

0.6899034666990468

In [30]:
bagmodel=BaggingClassifier(
        base_estimator=SVC(),
        n_estimators=100,
        max_samples=0.8,
        oob_score=True,
        random_state=0
)
scores=cross_val_score(bagmodel,x,y,cv=5)
scores.mean()

C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

0.6887984943233562

In [31]:
scores=cross_val_score(DecisionTreeClassifier(),x,y,cv=5)
scores.mean()

0.7361483820047356

In [33]:
bagmodel=BaggingClassifier(
        base_estimator=DecisionTreeClassifier(),
        n_estimators=100,
        max_samples=0.8,
        oob_score=True,
        random_state=0  #bagging with Decision tree classifer.here bagging gives more score level than standalone  decesion tree
)
scores=cross_val_score(bagmodel,x,y,cv=5)
scores.mean()

C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

0.7946269200412848